# .github/workflows/5-deploy-push-server.yml
name: 5. Deploy Push Server
on:
  push:
    paths:
      - 'push_server/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Azure Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUSH_SERVER_HOST }}
          username: ${{ secrets.PUSH_SERVER_USER }}
          key: ${{ secrets.PUSH_SERVER_SSH_KEY }}
          envs: TELEGRAM_BOT_TOKEN
          script: |
            set -e

            APP_DIR="/home/webhook"
            REPO_URL="https://github.com/${{ github.repository }}.git"
            BRANCH_NAME="${{ github.ref_name }}"

            echo "--- 正在部署机器人到 $APP_DIR ---"

            # 确保应用目录存在且权限正确
            sudo mkdir -p "$APP_DIR"
            sudo chown ${{ secrets.PUSH_SERVER_USER }}:${{ secrets.PUSH_SERVER_USER }} "$APP_DIR"
            cd "$APP_DIR"

            # 修正：采用更健壮的“原地初始化”方法
            if [ ! -d ".git" ]; then
              echo "Git 仓库不存在，正在进行初始化..."
              git init
              git remote add origin "$REPO_URL"
              echo "正在拉取最新的代码..."
              git fetch origin
              git reset --hard "origin/$BRANCH_NAME"
              # 确保本地分支跟踪远程分支
              git branch --set-upstream-to="origin/$BRANCH_NAME" "$BRANCH_NAME"
            else
              echo "Git 仓库已存在，正在拉取最新的代码..."
              git remote set-url origin "$REPO_URL"
              git fetch origin
              git reset --hard "origin/$BRANCH_NAME"
            fi
            
            echo "正在设置 Python 虚拟环境..."
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi
            
            source venv/bin/activate
            echo "正在安装/更新依赖..."
            pip install -r push_server/requirements.txt
            
            echo "正在创建 .env 文件..."
            echo "TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}" > push_server/.env

            echo "正在重启应用服务..."
            sudo systemctl restart webhook
            
            echo "🎉 部署成功！机器人已是最新版本！"
